name: PHPUnit

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:

  tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    env:
      extensions: amqp apcu gettext igbinary intl mbstring memcached xdebug
      phpunit_version: 9

    strategy:
      matrix:
        include:
          - php: '7.2'
          - php: '7.4'
          - php: '8.0'
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup PHP
        uses: php-actions/composer@v6
        with:
          memory_limit: 256M
          php_version: "${{ matrix.php }}"
          php_extensions: "${{ env.extensions }}"

      - name: Configure PHPUnit for PHP7.2
        if: "${{ matrix.php == '7.2' }}"
        run: |
          echo "phpunit_version=8" >> $GITHUB_ENV

      - name: Run Tests
        uses: php-actions/phpunit@v3
        env:
          XDEBUG_MODE: coverage
        with:
          args: --coverage-text
          memory_limit: 256M
          version: "${{ env.phpunit_version }}"
          php_version: "${{ matrix.php }}"
          php_extensions: "${{ env.extensions }}"
