name: PHPUnit

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:

  tests:
    name: Unit Tests
    runs-on: Ubuntu-20.04

    env:
      extensions: amqp apcu igbinary intl mbstring memcached xdebug

    strategy:
      matrix:
        include:
          - php: '7.2'
          - php: '8.0'
          - php: '7.4'
            mode: high-deps
          - php: '8.0'
            mode: low-deps
          - php: '8.1'
            mode: experimental
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Configure for PHP 8.1
        if: "${{ matrix.php == '8.1' }}"
        run: |
          echo "extensions=mbstring,xdebug" >> $GITHUB_ENV

      - name: Setup PHP
        uses: php-actions/composer@v5
        with:
          memory_limit: -1
          php_version: "${{ matrix.php }}"
          php_extensions: "${{ env.extensions }}"

      - name: Install dependencies
        run: composer install --no-progress

      - name: Run Tests
        uses: php-actions/phpunit@v3
        env:
          XDEBUG_MODE: coverage
        with:
          bootstrap: vendor/autoload.php
          args: --coverage-text
